In [3]:
import numpy as np
import cvxpy as cp

[Link to my GitHub Repository where notebook is locaated](https://github.com/johannesfuest/Applied_Optimization)


In [4]:
# Problem 1:

# Decision variables: quantities of each capsule type
x_EL = cp.Variable(name='Extra_Large')  # Extra-large capsules
x_L = cp.Variable(name='Large')         # Large capsules
x_M = cp.Variable(name='Medium')        # Medium capsules
x_S = cp.Variable(name='Small')         # Small capsules

# Profit coefficients
profit_coeffs = np.array([5, 4, 2, 0.5])

# Form the objective function
objective = cp.Maximize(
    profit_coeffs[0] * x_EL +
    profit_coeffs[1] * x_L +
    profit_coeffs[2] * x_M +
    profit_coeffs[3] * x_S
)

# Constraints
total_drug_constraint = 100 * x_EL + 60 * x_L + 30 * x_M + 10 * x_S <= 10000
large_capsules_constraint = x_L >= 2 * x_EL
medium_capsules_constraint = x_M >= 3 * x_L
small_capsules_constraint = x_S >= 100
non_negativity_constraints = [
    x_EL >= 0,
    x_L >= 0,
    x_M >= 0,
    x_S >= 0
]

constraints = [
    total_drug_constraint,
    large_capsules_constraint,
    medium_capsules_constraint,
    small_capsules_constraint
] + non_negativity_constraints

# Formulate and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Display the results
print("Optimal Quantities:")
print(f"Extra-large capsules (x_EL): {x_EL.value:.2f}")
print(f"Large capsules (x_L): {x_L.value:.2f}")
print(f"Medium capsules (x_M): {x_M.value:.2f}")
print(f"Small capsules (x_S): {x_S.value:.2f}")

print(f"\nMaximum Profit: ${problem.value:.2f}")

print(f"Since there are exactly 100 small capsules, this is a tight constraint.")
print(f"Since the number of large capsules is far greater than the number of extra-large capsules, this is a slack constraint.")
print(f" Since the number of medium capsules is more than three times the number of large capsules, this is a slack constraint.")

Optimal Quantities:
Extra-large capsules (x_EL): 0.00
Large capsules (x_L): 52.44
Medium capsules (x_M): 195.12
Small capsules (x_S): 100.00

Maximum Profit: $650.00
Since there are exactly 100 small capsules, this is a tight constraint.
Since the number of large capsules is far greater than the number of extra-large capsules, this is a slack constraint.
 Since the number of medium capsules is more than three times the number of large capsules, this is a slack constraint.


In [5]:
# TODO: maximize the minimum profit per charity

# Problem 2:

x_Ed = cp.Variable(name='Education')
x_Hl = cp.Variable(name='Healthcare')
x_Ev = cp.Variable(name='Environment')
x_min = cp.Variable(name='Minimum')

impact_coeffs = np.array([0.1, 0.08, 0.12])

maximum_constraints_1 = [
    x_Ed <= 50000,
    x_Hl <= 50000,
    x_Ev <= 50000,
]

maximum_constraints_2 = [
    x_Ed <= 60000,
    x_Hl <= 60000,
    x_Ev <= 60000,
]

minimum_constraints = [
    x_min <= impact_coeffs[0] * x_Ed,
    x_min <= impact_coeffs[1] * x_Hl,
    x_min <= impact_coeffs[2] * x_Ev,
]


total_constraint = x_Ed + x_Hl + x_Ev <= 100000

non_negative_constraints = [
    x_Ed >= 0,
    x_Hl >= 0,
    x_Ev >= 0,
]

objective = cp.Maximize(
    x_min
)

constraints_1 = (
    maximum_constraints_1 +
    [total_constraint] +
    non_negative_constraints + 
    minimum_constraints
)

constraints_2 = (
    maximum_constraints_2 +
    [total_constraint] +
    non_negative_constraints + 
    minimum_constraints
)

problem_1 = cp.Problem(objective, constraints_1)
problem_2 = cp.Problem(objective, constraints_2)

problem_1.solve()

print("\nExercise 2:")
print("\nCase 1:")
print(f"Optimal Quantities:")
print(f"Education (x_Ed): {x_Ed.value:.2f}")
print(f"Healthcare (x_Hl): {x_Hl.value:.2f}")
print(f"Environment (x_Ev): {x_Ev.value:.2f}")
print(f"\nMaximum Impact: {problem_1.value:.2f}")

problem_2.solve()
print("\nCase 2:")
print(f"Optimal Quantities:")
print(f"Education (x_Ed): {x_Ed.value:.2f}")
print(f"Healthcare (x_Hl): {x_Hl.value:.2f}")
print(f"Environment (x_Ev): {x_Ev.value:.2f}")
print(f"\nMaximum Impact: {problem_2.value:.2f}")

print(f"The distribution does not change when the maximum budget is set to $60000")


Exercise 2:

Case 1:
Optimal Quantities:
Education (x_Ed): 32432.43
Healthcare (x_Hl): 40540.54
Environment (x_Ev): 27027.03

Maximum Impact: 3243.24

Case 2:
Optimal Quantities:
Education (x_Ed): 32432.43
Healthcare (x_Hl): 40540.54
Environment (x_Ev): 27027.03

Maximum Impact: 3243.24
The distribution does not change when the maximum budget is set to $60000


In [6]:
# Problem 3:

x_1 = cp.Variable(name='project_1')
x_2 = cp.Variable(name='project_2')
x_3 = cp.Variable(name='project_3')
x_4 = cp.Variable(name='project_4')

benefit_coeffs = np.array([60, 50, 40, 35])
cost_coeffs = np.array([50000, 40000, 30000, 20000])

objective = cp.Maximize(
    benefit_coeffs[0] * x_1 +
    benefit_coeffs[1] * x_2 +
    benefit_coeffs[2] * x_3 +
    benefit_coeffs[3] * x_4
)

non_negative_constraints = [
    x_1 >= 0,
    x_2 >= 0,
    x_3 >= 0,
    x_4 >= 0,
]

total_cost_constraint = (
    cost_coeffs[0] * x_1 +
    cost_coeffs[1] * x_2 +
    cost_coeffs[2] * x_3 +
    cost_coeffs[3] * x_4 <= 100000
)

maximum_constraints = [
    x_1 <= 1,
    x_2 <= 1,
    x_3 <= 1,
    x_4 <= 1,
]

all_constraints = (
    non_negative_constraints +
    [total_cost_constraint] +
    maximum_constraints
)

problem = cp.Problem(objective, all_constraints)
problem.solve()

print("\nExercise 3:")
print(f"Optimal Quantities:")
print(f"Project 1 (x_1): {x_1.value:.2f}")
print(f"Project 2 (x_2): {x_2.value:.2f}")
print(f"Project 3 (x_3): {x_3.value:.2f}")
print(f"Project 4 (x_4): {x_4.value:.2f}")
print(f"Project 1 only gets partial funding, all others get fully funded")
print(f"\nMaximum Benefit is: {problem.value:.2f}")

fairness_constraints = [
    x_3 >= 1/3,
    x_1 * cost_coeffs[0] + x_2 * cost_coeffs[1] <= 60000,
    x_4 * cost_coeffs[3] >= x_3 * cost_coeffs[2],
]
all_constraints = (
    non_negative_constraints +
    [total_cost_constraint] +
    fairness_constraints + 
    maximum_constraints
)
problem_3 = cp.Problem(objective, all_constraints)
problem_3.solve()

print("\nFairness Constraints:")
print(f"Optimal Quantities:")
print(f"Project 1 (x_1): {x_1.value:.2f}")
print(f"Project 2 (x_2): {x_2.value:.2f}")
print(f"Project 3 (x_3): {x_3.value:.2f}")
print(f"Project 4 (x_4): {x_4.value:.2f}")

print(f"\nMaximum Benefit is: {problem_3.value:.2f}")





Exercise 3:
Optimal Quantities:
Project 1 (x_1): 0.20
Project 2 (x_2): 1.00
Project 3 (x_3): 1.00
Project 4 (x_4): 1.00
Project 1 only gets partial funding, all others get fully funded

Maximum Benefit is: 137.00

Fairness Constraints:
Optimal Quantities:
Project 1 (x_1): 0.40
Project 2 (x_2): 1.00
Project 3 (x_3): 0.67
Project 4 (x_4): 1.00

Maximum Benefit is: 135.67


In [1]:
import cvxpy as cp
import numpy as np

# Problem 4:

# Skill levels matrix (workers x projects)
skill_levels = np.array([
    [7, 6, 5],  # Worker 1
    [5, 8, 7],  # Worker 2
    [6, 5, 9],  # Worker 3
])

num_workers, num_projects = skill_levels.shape

# Decision variables matrix (workers x projects)
X = cp.Variable((num_workers, num_projects))

# Constraints
worker_constraints = [cp.sum(X, axis=1) == 1]  # Each worker assigned to exactly one project
project_constraints = [cp.sum(X, axis=0) == 1]  # Each project assigned to exactly one worker

non_negative_constraints = [X >= 0]
max_one_constraints = [X <= 1]

constraints = (
    worker_constraints + 
    project_constraints + 
    non_negative_constraints +
    max_one_constraints
)

# Objective function: maximize total skill level
objective = cp.Maximize(cp.sum(cp.multiply(skill_levels, X)))

# Formulate and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Display the results
optimal_skill = problem.value
optimal_assignment = X.value

print("Optimal Total Skill Level:", optimal_skill)
print("\nOptimal Assignment Matrix (Workers x Projects):\n", optimal_assignment)

# Interpret the assignments
for i in range(num_workers):
    for j in range(num_projects):
        if optimal_assignment[i, j] > 0.5:
            print(f"Worker {i+1} is assigned to Project {j+1}")

print("\nYes, there is an integer optimal solution. Yes, there is an integer basic feasible solution.")

# Part 2: Fair Assignment with Compensation and Satisfaction

# Worker preferences matrix
worker_preferences = np.array([
    [3, 8, 6],  # Worker 1
    [7, 5, 9],  # Worker 2
    [6, 6, 7],  # Worker 3
])

# Base salaries for projects
salaries = np.array([100000, 120000, 110000])

# Parameters
M = 10  # Maximum possible preference score

# Precompute compensation parameters
c_params = np.zeros((num_workers, num_projects))
for i in range(num_workers):
    for j in range(num_projects):
        c_params[i, j] = salaries[j] * (M - worker_preferences[i, j]) / M
    
# Variables for max and min compensation
max_c = cp.Variable()
min_c = cp.Variable()

# Delta constraints
delta_constraints = [
    max_c >= cp.sum(cp.multiply(X[0, :], c_params[0, :])),
    max_c >= cp.sum(cp.multiply(X[1, :], c_params[1, :])),
    max_c >= cp.sum(cp.multiply(X[2, :], c_params[2, :])),
    min_c <= cp.sum(cp.multiply(X[0, :], c_params[0, :])),
    min_c <= cp.sum(cp.multiply(X[1, :], c_params[1, :])),
    min_c <= cp.sum(cp.multiply(X[2, :], c_params[2, :])),
]

# Update constraints
constraints += delta_constraints

# List of alpha values to test
alpha_values = [0, 5e-5, 1]

for alpha in alpha_values:
    # Objective components
    total_skill = cp.sum(cp.multiply(skill_levels, X))
    delta = max_c - min_c
    
    # Objective function
    objective = cp.Maximize(alpha * total_skill - (1 - alpha) * delta)
    
    # Formulate and solve the problem
    problem = cp.Problem(objective, constraints)
    problem.solve()
    
    # Display the results
    optimal_value = problem.value
    optimal_assignment = X.value
    
    max_compensation = max_c.value
    min_compensation = min_c.value
    delta_value = max_compensation - min_compensation
    
    print(f"\nFor alpha = {alpha}:")
    print("Optimal Objective Value:", optimal_value)
    print("\nOptimal Assignment Matrix (Workers x Projects):\n", optimal_assignment)
    
    # Interpret the assignments
    for i in range(num_workers):
        for j in range(num_projects):
            if optimal_assignment[i, j] > 0.5:
                print(f"Worker {i+1} is assigned to Project {j+1}")
    
    print(f"Max Compensation: {max_compensation}")
    print(f"Min Compensation: {min_compensation}")
    print(f"Delta (Difference): {delta_value}")
    
    # Check if the solution is integer
    is_integer_solution = np.allclose(optimal_assignment, np.round(optimal_assignment))
    print(f"Is integer optimal solution: {is_integer_solution}")


Optimal Total Skill Level: 24.000000000305185

Optimal Assignment Matrix (Workers x Projects):
 [[ 9.99999999e-01  1.58544435e-09 -8.49512553e-10]
 [-2.62820460e-10  9.99999999e-01  9.98743403e-10]
 [ 9.98743416e-10 -8.49512548e-10  1.00000000e+00]]
Worker 1 is assigned to Project 1
Worker 2 is assigned to Project 2
Worker 3 is assigned to Project 3

Yes, there is an integer optimal solution. Yes, there is an integer basic feasible solution.

For alpha = 0:
Optimal Objective Value: 3.92901711165905e-10

Optimal Assignment Matrix (Workers x Projects):
 [[0.11354394 0.38706897 0.49938709]
 [0.46672255 0.39475581 0.13852164]
 [0.41973351 0.21817522 0.36209127]]
Max Compensation: 39210.762913132756
Min Compensation: 39210.76291313315
Delta (Difference): -3.92901711165905e-10
Is integer optimal solution: False

For alpha = 5e-05:
Optimal Objective Value: 0.0010211726053293902

Optimal Assignment Matrix (Workers x Projects):
 [[2.06758299e-01 7.41629742e-01 5.16119593e-02]
 [5.72832819e-01 2

In [8]:

w_1 = cp.Variable(name='Water_1')
f_1 = cp.Variable(name='Fertilizer_1')
w_2 = cp.Variable(name='Water_2')
f_2 = cp.Variable(name='Fertilizer_2')
w_3 = cp.Variable(name='Water_3')
f_3 = cp.Variable(name='Fertilizer_3')

min_1 = cp.Variable(name='Min_1')
min_2 = cp.Variable(name='Min_2')
min_3 = cp.Variable(name='Min_3')

min_overall = cp.Variable(name='Min_Overall')

yield_constraints = [
    min_1 <= 2 * w_1,
    min_1 <= 3 * f_1,
    min_2 <= 1.5 * w_2,
    min_2 <= 2 * f_2,
    min_3 <= 3 * w_3,
    min_3 <= 1.5 * f_3,
]

capacity_constraints = [
    w_1 + w_2 + w_3 <= 120,
    f_1 + f_2 + f_3 <= 90,
]

non_negative_constraints = [
    w_1 >= 0,
    f_1 >= 0,
    w_2 >= 0,
    f_2 >= 0,
    w_3 >= 0,
    f_3 >= 0,
    min_1 >= 0,
    min_2 >= 0,
    min_3 >= 0,
]

minimum_constraints = [
    min_overall <= min_1,
    min_overall <= min_2,
    min_overall <= min_3,
]

objective = cp.Maximize(min_overall)

constraints = (
    yield_constraints +
    capacity_constraints +
    non_negative_constraints +
    minimum_constraints
)

problem = cp.Problem(objective, constraints)

problem.solve()

print("\nExercise 5:")
print(f"Optimal Quantities:")
print(f"Water 1 (w_1): {w_1.value:}")
print(f"Fertilizer 1 (f_1): {f_1.value}")
print(f"Water 2 (w_2): {w_2.value:.2f}")
print(f"Fertilizer 2 (f_2): {f_2.value:.2f}")
print(f"Water 3 (w_3): {w_3.value:.2f}")
print(f"Fertilizer 3 (f_3): {f_3.value:.2f}")
print(f"Yield 1: {min_1.value:.2f}")
print(f"Yield 2: {min_2.value:.2f}")
print(f"Yield 3: {min_3.value:.2f}")
print(f"\n Yield overall: {problem.value:.2f}")


Exercise 5:
Optimal Quantities:
Water 1 (w_1): 35.4379145445711
Fertilizer 1 (f_1): 20.000000000056822
Water 2 (w_2): 45.98
Fertilizer 2 (f_2): 30.00
Water 3 (w_3): 24.32
Fertilizer 3 (f_3): 40.00
Yield 1: 60.00
Yield 2: 60.00
Yield 3: 60.00

 Yield overall: 60.00
